global_costmap:
  ros__parameters:
    global_frame: "map"
    robot_base_frame: "base_link"

    update_frequency: 25.0
    publish_frequency: 25.0
    transform_tolerance: 0.5

    static_map: true
    rolling_window: false  # Global costmap does NOT move with the robot
    width: 100.0
    height: 100.0
    resolution: 0.05

    # Define costmap layers explicitly for ROS 2
    plugins:
      - {name: static_layer, type: "nav2_costmap_2d::StaticLayer"}
      - {name: inflation_layer, type: "nav2_costmap_2d::InflationLayer"}

