%YAML:1.0

#-------------------------------------------------------------------------------------------- Camera Parameters. Adjust them! 
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 800.3645
Camera.fy: 799.8122
Camera.cx: 647.2679
Camera.cy: 349.6318

# OAK-D has minimal distortion, but if needed, adjust from calibration
Camera.k1: 0.0 #22.420289993286133
Camera.k2: 0.0 #-30.014972686767578
Camera.p1: 0.0 #0.0007826939690858126
Camera.p2: 0.0 #-0.0005663413903675973
Camera.k3: 0.0 #8.271049499511719

# Disable FishEye model
Camera.bFishEye: 0

# Camera Resolution
Camera.width: 1280
Camera.height: 720

# Camera frames per second 
Camera.fps: 10.0   # OAK-D supports 30 FPS, increase for better tracking
#KeyFrame.insert_threshold: 0.001  # Reduce to insert keyframes faster
# Stereo baseline times fx (bf = Baseline * fx)
Camera.bf: 60.0273375  # OAK-D baseline (7.5cm) * fx (800.3645)

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1  # OAK-D outputs RGB images

# Close/Far threshold. Baseline times.
ThDepth: 18.0  # Adjusted to match KITTI-like depth range

#InsertKFsWhenLost: 4
# Transformation from camera 0 to body-frame (imu)
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [1.0, 0.0, 0.0, -0.05,
          0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 1.0, -0.001,
          0.0, 0.0, 0.0, 1.0]

# IMU noise

IMU.NoiseGyro: 1.4e-4  #-4  # Gyroscope noise (from 0.008 dps/√Hz)
IMU.NoiseAcc: 1.57e-3 # -3  # Accelerometer noise (from 160 μg/√Hz)
IMU.GyroWalk: 8.7e-3 #-3  # Gyroscope bias instability (from ±0.5 dps)
IMU.AccWalk: 2.0e-1  # -1  # Accelerometer bias instability (from ±20 mg)
IMU.Frequency: 100     # Match the IMU sampling rate


#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2200

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

