controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    ackermann_steering_controller:
      type: 'ackermann_steering_controller/AckermannSteeringController'

ackermann_steering_controller:
  ros__parameters:
    wheelbase: 0.645
    front_wheel_track: 0.605
    rear_wheel_track: 0.605
    front_wheels_radius: 0.165
    rear_wheels_radius: 0.165
    front_steering: true
    reference_timeout: 1.0
    rear_wheels_names: ['rear_left_wheel_bearing', 'rear_right_wheel_bearing']
    front_wheels_names: ['front_left_steer_bearing', 'front_right_steer_bearing']
    use_stamped_vel: true
    open_loop: false
    velocity_rolling_window_size: 10
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    position_feedback: false

