ekf_filter_node:
  ros__parameters:
    sensor_timeout: 0.01
    frequency: 50.0
    two_d_mode: true
    publish_tf: true
    world_frame: "odom"
    odom_frame: "odom" # for fusion the wheel odometry should publish to a custom frame id like wheel_odom then localization wheel pulish wheel_odom to base_link
    base_link_frame: "base_link"

    #        [x_pos   , y_pos    , z_pos,
    #         roll    , pitch    , yaw,
    #         x_vel   , y_vel    , z_vel,
    #         roll_vel, pitch_vel, yaw_vel,
    #         x_accel , y_accel  , z_accel]

    #robot
    odom0: "/ov_msckf/loop_pose"
    #odom0: "/ov_msckf/odomimu"

    odom0_config: [true, true, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    odom0_nodelay: false
    odom0_differential: false
    odom0_queue_size: 5
    odom0_relative: false


    #use_control: true
    #stamped_control: false


    #control_timeout: 0.0002
    #control_config: [true, false, false, false, false, true]

    # Places limits on how large the acceleration term will be. Should match your robot's kinematics.
    #acceleration_limits: [10.0, 0.0, 0.0, 0.0, 0.0, 10.0]
    #deceleration_limits: [10.0, 0.0, 0.0, 0.0, 0.0, 10.0]
    #acceleration_gains: [0.8, 0.0, 0.0, 0.0, 0.0, 0.9]
    #deceleration_gains: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0]

    # robot
    imu_frame: "id100_sensor_link"
    imu0: "olive/imu/id100/filtered_imu"

    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]

    imu0_nodelay: false
    imu0_relative: true
    imu0_queue_size: 20
    imu0_pose_rejection_threshold: 0.5
    imu0_twist_rejection_threshold: 0.5
    imu0_linear_acceleration_rejection_threshold: 0.5
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
    dynamic_process_noise_covariance: true

    print_diagnostics: false
    debug: false

    # ordered as x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az. Defaults to the matrix below if
    process_noise_covariance: [0.05,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.05,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.05,   0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.02,   0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.02,   0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.02,    0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.02,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.03,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.02,   0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.02,   0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.02,   0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.02,   0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.02,   0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.02]

